### ISSUE TITLE
Polygons not rendering properly (Mac OSX, pygame)

### ISSUE THREAD

**Issue by jchirik** [pybox2d/pybox2d#103]
Polygon shapes in the included examples don't render correctly using pygame (edges seem to be randomly offset from their true positions). 
It doesn't have any effect on pybox2d physics, and pyglet renders them fine.

Pyramid (should all be squares):
<img width="505" alt="screen shot 2018-07-11 at 3 30 30 pm" src="https://user-images.githubusercontent.com/5505304/42577448-a52c0ce8-8524-11e8-8474-8f5fa8f5db2b.png">
Pinball (should be rectangular bars):
<img width="632" alt="screen shot 2018-07-11 at 3 29 48 pm" src="https://user-images.githubusercontent.com/5505304/42577454-a823aabe-8524-11e8-8d39-2d4e89f14e0f.png">

**Comment by kne** [comment]
Here's pybox2d 2.3.10 with pygame 1.9.6 on OSX Catalina:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/76203/78460409-8d2cdc00-7675-11ea-8584-90459d70c1d8.png">

Looks like a more recent pygame version may have fixed this - as the issue is nearing 2 years old at this point.

If you (or anyone else) has this issue on the above versions, please re-open.
