### ISSUE TITLE
ContactManagers are broken with multiple worlds (Segfault)

### ISSUE THREAD

**Issue by geratheon** [pybox2d/pybox2d#110]
When using multiple worlds, you can't use any contact managers since they're segfaulting. I know, multiple worlds aren't usually a thing, but when using reinforcement learning, they are.

A minimal code example which ends up crashing with a `Segmentation fault: 11`:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from Box2D import *

class Segfaulter:
    def __init__(self):
        self.world = b2World(contactListener=b2ContactListener())
        body1 = self.world.CreateDynamicBody(position=(0, 0))
        body1.CreateCircleFixture()
        body2 = self.world.CreateDynamicBody(position=(0, 0))
        body2.CreateCircleFixture()

    def step(self):
        self.world.Step(1 / 30, velocityIterations=1, positionIterations=1)

segfaulter1 = Segfaulter()
segfaulter2 = Segfaulter()
segfaulter1.step()
segfaulter2.step()
```

I'm currently using Python 3.7.4 on Mac OS X 10.14.3 with pybox2d 2.3.8.

If you don't use the contactListener kwarg in the b2World constructor, everything works fine, but then you have to sort out the collisions yourself and might miss some.

**Comment by kne** [comment]
Thanks for the report. Reproduced it locally. I'll poke around and see what I can find.

**Comment by kne** [comment]
Longer story:
Turns out this was a newbie mistake of mine from roughly 12 years ago, believing that a class-body-defined `dict` would be the same as defining `self.d = {}` in the initializer.

That dictionary was stashing a reference to contact listeners (and others) so the caller did not have to. So when you used a contact manager in multiple worlds without stashing your own reference of it, the first one would be automatically destroyed as the first instance fell out of the class-defined dictionary. 🤦‍♂
